var key = argument0;
//if (key == vk_rcontrol) return 7;
//else if (key == vk_lcontrol) return 9;
//else if (key == vk_rshift) return 13;
//else if (key == vk_lshift) return 25;
if (key = vk_enter) return 45;
if (key = vk_right) return 3;
if (key = vk_left) return 4;
if (key = vk_down) return 5;
if (key = vk_up) return 6;
if (key = vk_tab) return 58;
if (key = vk_space) return 8;
if (key = vk_backspace) return 62;
if (chr(key) == "A") return 40;
if (chr(key) == "B") return 19;
if (chr(key) == "C") return 21;
if (chr(key) == "D") return 38;
if (chr(key) == "E") return 55;
if (chr(key) == "F") return 37;
if (chr(key) == "G") return 36;
if (chr(key) == "H") return 35;
if (chr(key) == "I") return 50;
if (chr(key) == "J") return 34;
if (chr(key) == "K") return 33;
if (chr(key) == "L") return 32;
if (chr(key) == "M") return 17;
if (chr(key) == "N") return 18;
if (chr(key) == "O") return 49;
if (chr(key) == "P") return 48;
if (chr(key) == "Q") return 57;
if (chr(key) == "R") return 54;
if (chr(key) == "S") return 39;
if (chr(key) == "T") return 53;
if (chr(key) == "U") return 51;
if (chr(key) == "V") return 20;
if (chr(key) == "W") return 56;
if (chr(key) == "X") return 22;
if (chr(key) == "Y") return 52;
if (chr(key) == "Z") return 23;
if (key == ord("0")) return 65;
if (key == ord("9")) return 66;
if (key == ord("8")) return 67;
if (key == ord("7")) return 68;
if (key == ord("6")) return 69;
if (key == ord("5")) return 70;
if (key == ord("4")) return 71;
if (key == ord("3")) return 72;
if (key == ord("2")) return 73;
if (key == ord("1")) return 74;
show_debug_message(key)

//ds_map_add(keyToIndex,ord("/"),14);
//ds_map_add(keyToIndex,ord("."),15);
//ds_map_add(keyToIndex,ord(","),16);
//ds_map_add(keyToIndex,ord("\\"),24);
//ds_map_add(keyToIndex,ord("\\"),29);
//ds_map_add(keyToIndex,ord("'"),30);
//ds_map_add(keyToIndex,ord(";"),31);
//ds_map_add(keyToIndex,ord("]"),46);
//ds_map_add(keyToIndex,ord("["),47);
//ds_map_add(keyToIndex,ord("="),63);
//ds_map_add(keyToIndex,ord("-"),64);
//ds_map_add(keyToIndex,ord("0"),65);
//ds_map_add(keyToIndex,ord("9"),66);
//ds_map_add(keyToIndex,ord("8"),67);
//ds_map_add(keyToIndex,ord("7"),68);
//ds_map_add(keyToIndex,ord("6"),69);
//ds_map_add(keyToIndex,ord("5"),70); 
//ds_map_add(keyToIndex,ord("4"),71); 
//ds_map_add(keyToIndex,ord("3"),72); 
//ds_map_add(keyToIndex,ord("2"),73);
//ds_map_add(keyToIndex,ord("1"),74);
//ds_map_add(keyToIndex,ord("`"),75); 